import re, urllib.request, urllib.parse, http.cookiejar
cj = http.cookiejar.CookieJar()
op = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cj))
import os as _os; base = _os.environ.get('RETROBB_TEST_BASE', 'http://localhost:8080')
html = op.open(base + '/login').read().decode()
tok = re.search(r'name="csrf" value="([^"]+)"', html).group(1)
data = urllib.parse.urlencode({'csrf': tok, 'login': 'admin', 'password': 'admin123', 'next': '/'}).encode()
op.open(urllib.request.Request(base + '/login', data=data))
dash = op.open(base + '/admin').read().decode()
print('dashboard 200:', 'Dashboard' in dash)
struct = op.open(base + '/admin/structure').read().decode()
print('structure rows:', struct.count('struct-cat'))
print('no stray topic-row:', 'topic-row' not in struct)
users = op.open(base + '/admin/users').read().decode()
print('users listed:', 'dialup_dan' in users)
print('modlog page:', 'Mod log' in op.open(base + '/admin/modlog').read().decode())
print('bans page:', 'Bans' in op.open(base + '/admin/bans').read().decode())
